# Generated by Django 4.2.1 on 2023-06-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAfectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=50)),
                ('cantidadQuintales', models.FloatField()),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
